---
- name: Install dependency packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python-setuptools
      - curl
      - gnupg2
      - software-properties-common
    state: present
  become: yes
  tags: ["docker","apt"]

- name: Remove default python-pip
  apt:
    name: "python-pip"
    state: absent
  become: yes
  tags: ["docker","apt"]

- name: Get pip installer script
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: /usr/local/sbin/
  become: yes
  register: get_pip_installer_script
  tags: ["docker", "pip"]

- name: Install pip
  shell: >
    python /usr/local/sbin/get-pip.py
  become: yes
  when: get_pip_installer_script.changed
  tags: ["docker", "pip"]

- name: Remove old docker apt source(s)
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    regexp: ".*apt.dockerproject.org/repo.*"
    state: absent
  become: yes
  register: remove_old_docker_apt_source
  tags: ["docker","apt"]

- name: Add apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id|lower }}/gpg"
  become: yes
  register: add_apt_key
  tags: ["docker","apt"]

- name: Add docker apt source
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename }} stable"
    filename: docker
  become: yes
  register: add_docker_apt_source
  tags: ["docker","apt"]

- name: Update apt cache if docker apt source added
  apt:
    update_cache: yes
  become: yes
  when: (add_docker_apt_source.changed) or
        (remove_old_docker_apt_source.changed) or
        (add_apt_key.changed)
  tags: ["docker","apt","skip_ansible_lint"]

- name: Remove old docker installations
  apt:
    name:
      - lxc-docker
      - docker.io
      - docker-engine
      - docker
    state: absent
  become: yes
  tags: ["docker","apt"]

- name: Install docker community edition
  apt:
    name: docker-ce
    state: present
    force: yes
  become: yes
  tags: ["docker","apt"]
